import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { stableStringify } from "@surfaces/interfacectl-extractor";
import { emitContractRunArtifact, type RunArtifactStatus, type RunArtifactSource } from "./run-artifacts.js";
type ValidationOutcome = RunArtifactStatus;
export type OnboardingRunSource = RunArtifactSource;

export interface BootstrapExtractionReport {
  surfaceId: string;
  appRoot: string;
  warnings: { code: string; message: string }[];
  extracted: {
    routes: string[];
    hasShell: boolean;
    designSystemComponents: string[];
    authAware: boolean;
  };
  onboarding: {
    sourceUrl: string;
    authMode: "none" | "browser-session";
    extractMode: "remote-url" | "local-root";
    profileName?: string;
    profileDomain?: string;
    startedAt: string;
    completedAt: string;
    detection: {
      adapter: string;
      framework: string;
      profile: string;
    };
  };
}

async function writeJsonAtomic(filePath: string, payload: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const tempPath = `${filePath}.tmp`;
  await writeFile(tempPath, `${stableStringify(payload)}\n`, "utf-8");
  await rename(tempPath, filePath);
}

async function readJson<T>(filePath: string, fallback: T): Promise<T> {
  if (!existsSync(filePath)) return fallback;
  try {
    const raw = await readFile(filePath, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

function sha256FromContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

export function suggestSurfaceIdFromUrl(rawUrl: string): string {
  const url = new URL(rawUrl);
  const host = url.hostname.replace(/^www\./, "");
  const pathToken = url.pathname
    .split("/")
    .map((token) => token.trim())
    .filter(Boolean)[0];
  const candidate = [host.replace(/\./g, "-"), pathToken]
    .filter(Boolean)
    .join("-");
  const normalized = candidate
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return normalized.length > 0 ? normalized : "surface";
}

export function suggestSurfaceName(surfaceId: string): string {
  return surfaceId
    .split("-")
    .filter(Boolean)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(" ");
}

export function suggestSurfaceIdFromPath(rawPath: string): string {
  const candidate = path.basename(rawPath);
  const normalized = candidate
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return normalized.length > 0 ? normalized : "surface";
}

export function buildBootstrapContract(input: {
  surfaceId: string;
  surfaceName: string;
  sourceUrl: string;
  authAware: boolean;
}): Record<string, unknown> {
  const url = new URL(input.sourceUrl);
  return {
    $schema:
      "https://contracts.surfaces.local/web.surface.contract.schema.json",
    contractId: `${input.surfaceId}.generated`,
    version: "0.1.0",
    description: "Generated by interfacectl init onboarding bootstrap.",
    surfaces: [
      {
        id: input.surfaceId,
        displayName: input.surfaceName,
        type: "web",
        domain: url.origin,
        requiredSections: ["extracted.placeholder"],
        allowedFonts: ["sans-serif"],
        layout: { maxContentWidth: 1120 },
      },
    ],
    sections: [
      {
        id: "extracted.placeholder",
        intent: "extracted",
        description: "Placeholder; sections are not inferred during URL onboarding bootstrap.",
      },
    ],
    constraints: {
      motion: {
        allowedDurationsMs: [120],
        allowedTimingFunctions: ["linear"],
      },
    },
    color: {
      policy: "warn",
      allowedValues: [],
    },
    x_extracted: {
      routes: [url.pathname || "/"],
      hasShell: false,
      designSystemComponents: [],
      authAware: input.authAware,
    },
    x_onboarding: {
      sourceUrl: input.sourceUrl,
      mode: "bootstrap",
    },
  };
}

export async function writeBootstrapArtifacts(input: {
  rootDir: string;
  outDir?: string;
  surfaceId: string;
  contract: Record<string, unknown>;
  report: BootstrapExtractionReport;
}): Promise<{
  contractPath: string;
  reportPath: string;
}> {
  const generatedDir = input.outDir
    ? path.resolve(input.rootDir, input.outDir)
    : path.resolve(input.rootDir, "contracts", "generated");
  const contractPath = path.join(generatedDir, `${input.surfaceId}.contract.json`);
  const reportPath = path.join(generatedDir, `${input.surfaceId}.extraction.json`);
  await writeJsonAtomic(contractPath, input.contract);
  await writeJsonAtomic(reportPath, input.report);
  return { contractPath, reportPath };
}

export async function emitOnboardingRunArtifact(input: {
  rootDir: string;
  surfaceId: string;
  source: OnboardingRunSource;
  status: ValidationOutcome;
  findingCodes: string[];
  extractionPath: string;
  reportPath: string;
}): Promise<{ runId: string }> {
  const result = emitContractRunArtifact({
    rootDir: input.rootDir,
    surfaceId: input.surfaceId,
    source: input.source,
    status: input.status,
    findingCodes: input.findingCodes,
    extractionPath: input.extractionPath,
    reportPath: input.reportPath,
  });
  return { runId: result.runId };
}

export async function emitBootstrapRunArtifact(input: {
  rootDir: string;
  surfaceId: string;
  status: ValidationOutcome;
  findingCodes: string[];
  extractionPath: string;
  reportPath: string;
}): Promise<{ runId: string }> {
  return emitOnboardingRunArtifact({
    ...input,
    source: "bootstrap",
  });
}
