import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { stableStringify } from "@surfaces/interfacectl-extractor";

type ValidationOutcome = "pass" | "warn" | "fail" | "unknown";
type RunSource = "bootstrap" | "generation" | "ci" | "runtime";

interface ContractRunsDocument {
  schemaVersion: number;
  runs: ContractRun[];
}

interface ContractRun {
  runId: string;
  createdAt: string;
  surfaceId: string;
  source: RunSource;
  contract: {
    id: string;
    version: string;
    sha256: string;
  };
  artifacts: {
    extractionPath?: string;
    reportPath?: string;
  };
  status: ValidationOutcome;
  findingCodes: string[];
  summary: {
    errorCount: number;
    warnCount: number;
  };
}

interface ContractLineageDocument {
  schemaVersion: number;
  surfaces: Record<string, {
    lastRunId: string;
    lastRunAt: string;
    lastSource: RunSource;
    lastStatus: ValidationOutcome;
    contract: {
      id: string;
      version: string;
      sha256: string;
    };
    artifacts: {
      extractionPath?: string;
      reportPath?: string;
    };
    findingCodes: string[];
  }>;
}

export interface BootstrapExtractionReport {
  surfaceId: string;
  appRoot: string;
  warnings: { code: string; message: string }[];
  extracted: {
    routes: string[];
    hasShell: boolean;
    designSystemComponents: string[];
    authAware: boolean;
  };
  onboarding: {
    sourceUrl: string;
    authMode: "none" | "browser-session";
    extractMode: "remote-url" | "local-root";
    profileName?: string;
    profileDomain?: string;
    startedAt: string;
    completedAt: string;
    detection: {
      adapter: string;
      framework: string;
      profile: string;
    };
  };
}

function statusSummary(status: ValidationOutcome, findingCodes: string[]) {
  return {
    errorCount: status === "fail" ? Math.max(1, findingCodes.length) : 0,
    warnCount: status === "warn" ? Math.max(1, findingCodes.length) : 0,
  };
}

async function writeJsonAtomic(filePath: string, payload: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const tempPath = `${filePath}.tmp`;
  await writeFile(tempPath, `${stableStringify(payload)}\n`, "utf-8");
  await rename(tempPath, filePath);
}

async function readJson<T>(filePath: string, fallback: T): Promise<T> {
  if (!existsSync(filePath)) return fallback;
  try {
    const raw = await readFile(filePath, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

function sha256FromContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function toRelative(root: string, candidate: string): string {
  return path.relative(root, candidate);
}

export function suggestSurfaceIdFromUrl(rawUrl: string): string {
  const url = new URL(rawUrl);
  const host = url.hostname.replace(/^www\./, "");
  const pathToken = url.pathname
    .split("/")
    .map((token) => token.trim())
    .filter(Boolean)[0];
  const candidate = [host.replace(/\./g, "-"), pathToken]
    .filter(Boolean)
    .join("-");
  const normalized = candidate
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return normalized.length > 0 ? normalized : "surface";
}

export function suggestSurfaceName(surfaceId: string): string {
  return surfaceId
    .split("-")
    .filter(Boolean)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(" ");
}

export function buildBootstrapContract(input: {
  surfaceId: string;
  surfaceName: string;
  sourceUrl: string;
  authAware: boolean;
}): Record<string, unknown> {
  const url = new URL(input.sourceUrl);
  return {
    $schema:
      "https://contracts.surfaces.local/web.surface.contract.schema.json",
    contractId: `${input.surfaceId}.generated`,
    version: "0.1.0",
    description: "Generated by interfacectl init onboarding bootstrap.",
    surfaces: [
      {
        id: input.surfaceId,
        displayName: input.surfaceName,
        type: "web",
        domain: url.origin,
        requiredSections: ["extracted.placeholder"],
        allowedFonts: ["sans-serif"],
        layout: { maxContentWidth: 1120 },
      },
    ],
    sections: [
      {
        id: "extracted.placeholder",
        intent: "extracted",
        description: "Placeholder; sections are not inferred during URL onboarding bootstrap.",
      },
    ],
    constraints: {
      motion: {
        allowedDurationsMs: [120],
        allowedTimingFunctions: ["linear"],
      },
    },
    color: {
      policy: "warn",
      allowedValues: [],
    },
    x_extracted: {
      routes: [url.pathname || "/"],
      hasShell: false,
      designSystemComponents: [],
      authAware: input.authAware,
    },
    x_onboarding: {
      sourceUrl: input.sourceUrl,
      mode: "bootstrap",
    },
  };
}

export async function writeBootstrapArtifacts(input: {
  rootDir: string;
  outDir?: string;
  surfaceId: string;
  contract: Record<string, unknown>;
  report: BootstrapExtractionReport;
}): Promise<{
  contractPath: string;
  reportPath: string;
}> {
  const generatedDir = input.outDir
    ? path.resolve(input.rootDir, input.outDir)
    : path.resolve(input.rootDir, "contracts", "generated");
  const contractPath = path.join(generatedDir, `${input.surfaceId}.contract.json`);
  const reportPath = path.join(generatedDir, `${input.surfaceId}.extraction.json`);
  await writeJsonAtomic(contractPath, input.contract);
  await writeJsonAtomic(reportPath, input.report);
  return { contractPath, reportPath };
}

async function readCanonicalContract(rootDir: string): Promise<{
  id: string;
  version: string;
  sha256: string;
}> {
  const canonicalPath = path.resolve(rootDir, "contracts", "surfaces.web.contract.json");
  if (!existsSync(canonicalPath)) {
    return { id: "unknown", version: "unknown", sha256: "0".repeat(64) };
  }
  try {
    const raw = await readFile(canonicalPath, "utf-8");
    const parsed = JSON.parse(raw) as { contractId?: string; version?: string };
    return {
      id: parsed.contractId ?? "unknown",
      version: parsed.version ?? "unknown",
      sha256: sha256FromContent(raw),
    };
  } catch {
    return { id: "unknown", version: "unknown", sha256: "0".repeat(64) };
  }
}

export async function emitBootstrapRunArtifact(input: {
  rootDir: string;
  surfaceId: string;
  status: ValidationOutcome;
  findingCodes: string[];
  extractionPath: string;
  reportPath: string;
}): Promise<{ runId: string }> {
  const generatedDir = path.resolve(input.rootDir, "contracts", "generated");
  const runsPath = path.join(generatedDir, "contract-runs.json");
  const lineagePath = path.join(generatedDir, "contract-lineage.json");

  const runsDoc = await readJson<ContractRunsDocument>(runsPath, {
    schemaVersion: 1,
    runs: [],
  });
  const lineageDoc = await readJson<ContractLineageDocument>(lineagePath, {
    schemaVersion: 1,
    surfaces: {},
  });

  const runId = randomUUID();
  const createdAt = new Date().toISOString();
  const canonical = await readCanonicalContract(input.rootDir);
  const runRecord: ContractRun = {
    runId,
    createdAt,
    surfaceId: input.surfaceId,
    source: "bootstrap",
    contract: canonical,
    artifacts: {
      extractionPath: toRelative(input.rootDir, input.extractionPath),
      reportPath: toRelative(input.rootDir, input.reportPath),
    },
    status: input.status,
    findingCodes: [...input.findingCodes].sort(),
    summary: statusSummary(input.status, input.findingCodes),
  };

  const deduped = runsDoc.runs.filter((run) => run.runId !== runId);
  deduped.push(runRecord);
  deduped.sort((a, b) => {
    const timeDiff = Date.parse(a.createdAt) - Date.parse(b.createdAt);
    if (timeDiff !== 0) return timeDiff;
    return a.runId.localeCompare(b.runId);
  });
  runsDoc.runs = deduped;
  lineageDoc.surfaces[input.surfaceId] = {
    lastRunId: runRecord.runId,
    lastRunAt: runRecord.createdAt,
    lastSource: runRecord.source,
    lastStatus: runRecord.status,
    contract: runRecord.contract,
    artifacts: runRecord.artifacts,
    findingCodes: runRecord.findingCodes,
  };

  await writeJsonAtomic(runsPath, runsDoc);
  await writeJsonAtomic(lineagePath, lineageDoc);
  return { runId };
}
